export const ROUTES = {
    HOMEPAGE_ROUTE: '/',
    DASHBOARDPAGE_ROUTE: '/dashboard',
    SETTINGSPAGE_ROUTE: '/settings',
    ADDMEMBER_ROUTE: '/add-member',
    MODIFYMEMBER_ROUTE: '/modify-member',
    MEMBERS_ROUTE: '/members',
    SESSIONS_ROUTE: '/sessions',
    EDITMEMBERS_ROUTE: '/edit-members',
    CONFIGS_ROUTE: '/configs',
    VIEW_MEMBER: '/view-member',
    VIEW_USER: '/view-user',
    VIEW_GAME_DETAILS: '/view-game-details',
    VIEW_COACHING_DETAILS: '/get-coaching-schedule',
    VIEW_TRAINING_DETAILS: '/get-training-schedule',
}